CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "ApplicationPage" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PageName" text NOT NULL,
    "PageCode" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "routePath" text NOT NULL,
    "menuPath" text NOT NULL,
    "isMenuPage" boolean NOT NULL,
    "componentName" text NOT NULL,
    CONSTRAINT "PK_ApplicationPage" PRIMARY KEY ("Id")
);

CREATE TABLE "Designations" (
    "designationId" integer GENERATED BY DEFAULT AS IDENTITY,
    "designationName" text NOT NULL,
    "designationCode" text NOT NULL,
    "isActive" boolean NOT NULL,
    CONSTRAINT "PK_Designations" PRIMARY KEY ("designationId")
);

CREATE TABLE "EmailModels" (
    "emailId" integer GENERATED BY DEFAULT AS IDENTITY,
    "SenderEmail" text NOT NULL,
    "RecipientEmail" text NOT NULL,
    "Subject" text NOT NULL,
    "Body" text NOT NULL,
    CONSTRAINT "PK_EmailModels" PRIMARY KEY ("emailId")
);

CREATE TABLE "EmployeeReporting" (
    "EmployeeReportingId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" bigint NOT NULL,
    "ReportingPersonId" bigint NOT NULL,
    CONSTRAINT "PK_EmployeeReporting" PRIMARY KEY ("EmployeeReportingId")
);

CREATE TABLE "FinancialYears" (
    "financialYearId" integer GENERATED BY DEFAULT AS IDENTITY,
    "startDate" date NOT NULL,
    "endDate" date NOT NULL,
    "ActiveYear" boolean NOT NULL,
    CONSTRAINT "PK_FinancialYears" PRIMARY KEY ("financialYearId")
);

CREATE TABLE "Genders" (
    "genderId" integer GENERATED BY DEFAULT AS IDENTITY,
    "genderCode" text NOT NULL,
    "genderName" text NOT NULL,
    "isActive" boolean NOT NULL,
    CONSTRAINT "PK_Genders" PRIMARY KEY ("genderId")
);

CREATE TABLE "Holidays" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "HolidayName" text NOT NULL,
    "HolidayDate" timestamp without time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Holidays" PRIMARY KEY ("Id")
);

CREATE TABLE "LeaveTypes" (
    "leaveTypeId" integer GENERATED BY DEFAULT AS IDENTITY,
    "leaveTypeName" character varying(255) NOT NULL,
    "leaveTypeNameCode" text NOT NULL,
    "isActive" boolean NOT NULL,
    CONSTRAINT "PK_LeaveTypes" PRIMARY KEY ("leaveTypeId")
);

CREATE TABLE "RoleAssign" (
    "RoleAssignId" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleAssignName" text NOT NULL,
    "RoleAssignCodeName" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsSuperAdmin" boolean NOT NULL,
    CONSTRAINT "PK_RoleAssign" PRIMARY KEY ("RoleAssignId")
);

CREATE TABLE "Tests" (
    "employeeId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "employeeCode" text NOT NULL,
    "firstName" character varying(255) NOT NULL,
    CONSTRAINT "PK_Tests" PRIMARY KEY ("employeeId")
);

CREATE TABLE "LeaveAllocations" (
    "leaveAllocationId" integer GENERATED BY DEFAULT AS IDENTITY,
    "financialYearId" integer NOT NULL,
    "leaveTypeId" integer NOT NULL,
    "leaveCount" integer NOT NULL,
    CONSTRAINT "PK_LeaveAllocations" PRIMARY KEY ("leaveAllocationId"),
    CONSTRAINT "FK_LeaveAllocations_FinancialYears_financialYearId" FOREIGN KEY ("financialYearId") REFERENCES "FinancialYears" ("financialYearId") ON DELETE CASCADE,
    CONSTRAINT "FK_LeaveAllocations_LeaveTypes_leaveTypeId" FOREIGN KEY ("leaveTypeId") REFERENCES "LeaveTypes" ("leaveTypeId") ON DELETE CASCADE
);

CREATE TABLE "Employees" (
    "employeeId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "employeeCode" text NOT NULL,
    "firstName" character varying(255) NOT NULL,
    "emailAddress" character varying(255) NOT NULL,
    "mobileNo" character varying(255) NOT NULL,
    "lastName" character varying(255) NOT NULL,
    "genderId" integer NOT NULL,
    "designationId" integer NOT NULL,
    "isActive" boolean NOT NULL,
    "dateOfJoining" date NOT NULL,
    "dateOfBirth" date NOT NULL,
    "employeePassword" text NOT NULL,
    "RoleAssignId" integer NOT NULL,
    "ReportingPersonId" bigint NULL,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("employeeId"),
    CONSTRAINT "FK_Employees_Designations_designationId" FOREIGN KEY ("designationId") REFERENCES "Designations" ("designationId") ON DELETE CASCADE,
    CONSTRAINT "FK_Employees_Genders_genderId" FOREIGN KEY ("genderId") REFERENCES "Genders" ("genderId") ON DELETE CASCADE,
    CONSTRAINT "FK_Employees_RoleAssign_RoleAssignId" FOREIGN KEY ("RoleAssignId") REFERENCES "RoleAssign" ("RoleAssignId") ON DELETE CASCADE
);

CREATE TABLE "UserRoleMapping" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ApplicationPageId" integer NOT NULL,
    "RoleAssignId" integer NOT NULL,
    CONSTRAINT "PK_UserRoleMapping" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserRoleMapping_ApplicationPage_ApplicationPageId" FOREIGN KEY ("ApplicationPageId") REFERENCES "ApplicationPage" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoleMapping_RoleAssign_RoleAssignId" FOREIGN KEY ("RoleAssignId") REFERENCES "RoleAssign" ("RoleAssignId") ON DELETE CASCADE
);

CREATE TABLE "AppliedLeaves" (
    "appliedLeaveTypeId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "employeeId" bigint NOT NULL,
    "leaveTypeId" integer NOT NULL,
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NOT NULL,
    "LeaveReason" character varying(256) NULL,
    "applyLeaveDay" double precision NOT NULL,
    "remaingLeave" double precision NOT NULL,
    "balanceLeave" double precision NOT NULL,
    "IsRejected" boolean NOT NULL,
    "IsApproved" boolean NOT NULL,
    "ApprovedNotes" text NULL,
    "RejectedNotes" text NULL,
    "ApprovedDate" timestamp without time zone NOT NULL,
    "RejectedDate" timestamp without time zone NOT NULL,
    "IsHalfDay" boolean NOT NULL,
    CONSTRAINT "PK_AppliedLeaves" PRIMARY KEY ("appliedLeaveTypeId"),
    CONSTRAINT "FK_AppliedLeaves_Employees_employeeId" FOREIGN KEY ("employeeId") REFERENCES "Employees" ("employeeId") ON DELETE CASCADE,
    CONSTRAINT "FK_AppliedLeaves_LeaveTypes_leaveTypeId" FOREIGN KEY ("leaveTypeId") REFERENCES "LeaveTypes" ("leaveTypeId") ON DELETE CASCADE
);

CREATE TABLE "EmployeeLeaves" (
    "employeeLeaveId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "employeeId" bigint NOT NULL,
    "leaveTypeId" integer NOT NULL,
    "leaveCount" double precision NOT NULL,
    "consumedLeaves" double precision NOT NULL,
    "balanceLeaves" double precision NOT NULL,
    "isActive" boolean NOT NULL,
    CONSTRAINT "PK_EmployeeLeaves" PRIMARY KEY ("employeeLeaveId"),
    CONSTRAINT "FK_EmployeeLeaves_Employees_employeeId" FOREIGN KEY ("employeeId") REFERENCES "Employees" ("employeeId") ON DELETE CASCADE,
    CONSTRAINT "FK_EmployeeLeaves_LeaveTypes_leaveTypeId" FOREIGN KEY ("leaveTypeId") REFERENCES "LeaveTypes" ("leaveTypeId") ON DELETE CASCADE
);

CREATE INDEX "IX_AppliedLeaves_employeeId" ON "AppliedLeaves" ("employeeId");

CREATE INDEX "IX_AppliedLeaves_leaveTypeId" ON "AppliedLeaves" ("leaveTypeId");

CREATE INDEX "IX_EmployeeLeaves_employeeId" ON "EmployeeLeaves" ("employeeId");

CREATE INDEX "IX_EmployeeLeaves_leaveTypeId" ON "EmployeeLeaves" ("leaveTypeId");

CREATE INDEX "IX_Employees_designationId" ON "Employees" ("designationId");

CREATE UNIQUE INDEX "IX_Employees_emailAddress" ON "Employees" ("emailAddress");

CREATE INDEX "IX_Employees_genderId" ON "Employees" ("genderId");

CREATE INDEX "IX_Employees_RoleAssignId" ON "Employees" ("RoleAssignId");

CREATE INDEX "IX_LeaveAllocations_financialYearId" ON "LeaveAllocations" ("financialYearId");

CREATE INDEX "IX_LeaveAllocations_leaveTypeId" ON "LeaveAllocations" ("leaveTypeId");

CREATE INDEX "IX_UserRoleMapping_ApplicationPageId" ON "UserRoleMapping" ("ApplicationPageId");

CREATE INDEX "IX_UserRoleMapping_RoleAssignId" ON "UserRoleMapping" ("RoleAssignId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231107085901_phase2', '7.0.12');

COMMIT;

START TRANSACTION;

ALTER TABLE "AppliedLeaves" ADD "IsCancelled" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231107090109_newColumnCancelledAdded', '7.0.12');

COMMIT;

START TRANSACTION;

ALTER TABLE "Tests" ADD description text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231107101214_testDescription', '7.0.12');

COMMIT;

START TRANSACTION;

ALTER TABLE "Tests" ADD "employeeName" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231107101731_EmployeeName', '7.0.12');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231108104155_settedDefualtValue', '7.0.12');

COMMIT;

